version: '3.9'

networks:
  inception-net:

volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jschneid/data/wp_volume
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jschneid/data/db_volume

services:
  mariadb:
      container_name: mariadb
      image: mariadb-image
      build: ./requirements/mariadb
      volumes:
        - db_volume:/var/lib/mysql
      networks:
        - inception-net
      restart: always

  nginx:
      container_name: nginx
      image: nginx-image
      build:
        context: ./requirements/nginx
      ports:
        - "443:443"
      volumes:
        - wp_volume:/var/www/wordpress
      depends_on:
        - wordpress
      networks:
        - inception-net
      restart: always

  wordpress:
      container_name: wordpress
      image: wordpress-image
      build:
        context: ./requirements/wordpress
      env_file:
        - .env
      volumes:
        - wp_volume:/var/www/wordpress
      depends_on:
        - mariadb
      ports:
        - "80:80"
      networks:
        - inception-net
      restart: always
